### ISSUE TITLE
Error thrown calling init with no group info (marked as optional)

### ISSUE THREAD

**Issue by alittlebrighter** [CarnegieLearningWeb/educational-experiment-service-client-libs#12]
When calling `init(userId, hostUrl)` the following error is printed in the console:
```
Error: TypeError: Cannot read property 'group' of undefined
```
Note, the AJAX call appears to work correctly and returns an object with a single `id` string property.

Looks as though the error is coming from here: https://github.com/CarnegieLearningWeb/educational-experiment-service-client-libs/blob/master/src/init.ts#L59

**Comment by jerith666** [comment]
Why isn't the typescript compiler catching this?

**Comment by kschaefe** [comment]
There is no strict checking in the `tsconfig`.  So it's about as loose as JS.

**Comment by jerith666** [comment]
@VivekFitkariwala, please adopt our stricter tsconfig from https://github.com/CarnegieLearningWeb/configs-public in this and all other UpGrade-related repos that contain TypeScript code.  Thanks!

**Comment by kschaefe** [comment]
Those don't have `strict` turned on yet, Matt.  That's on the list.

**Comment by jerith666** [comment]
Oh, I thought you were talking about the `tsconfig` that's currently in _this_ repo.

Maybe we ought to make a branch of our `configs-public` repo that does have `strict` turned on, so that new projects (like this one) can use that version?  cc @mhasko

**Comment by kschaefe** [comment]
I was, but directing them to a location that is also not strict isn't going to solve the problem.

**Comment by JD2455** [comment]
> When calling `init(userId, hostUrl)` the following error is printed in the console:
> 
> ```
> Error: TypeError: Cannot read property 'group' of undefined
> ```
> 
> Note, the AJAX call appears to work correctly and returns an object with a single `id` string property.
> 
> Looks as though the error is coming from here: https://github.com/CarnegieLearningWeb/educational-experiment-service-client-libs/blob/master/src/init.ts#L59

It is fixed in (https://github.com/CarnegieLearningWeb/educational-experiment-service-client-libs/pull/20)
