### ISSUE TITLE
Java client lib: should FailedExperimentPointRequest include a userId?

### ISSUE THREAD

**Issue by jerith666** [CarnegieLearningWeb/educational-experiment-service-client-libs#27]
I'm not 100% sure about this one, but it seems likely that we'll want to know the userId that the experiment point failed for.

`MarkExperimentPointRequest` [has this field](https://github.com/CarnegieLearningWeb/educational-experiment-service-client-libs/blob/master/java/src/main/java/requestbeans/MarkExperimentRequest.java#L10).

**Comment by VivekFitkariwala** [comment]
Library is updated to log userId along with other params. UserId will be used from the constructor call of client.
