### ISSUE TITLE
setWorkingGroup needs to support multiple values for each group

### ISSUE THREAD

**Issue by jerith666** [CarnegieLearningWeb/educational-experiment-service-client-libs#55]
For example, the `instructor` group may be multi-valued even after a student has decided to work in a single class, if the class is being taught by more than one instructor.

**Comment by VivekFitkariwala** [comment]
So the Experiment is a Group Experiment with `instructor`. And we want all the `instructor` assignments should be same right?
Or the Experiment is based on `class` as the group key?

**Comment by jerith666** [comment]
I'm not sure what the semantics of this should be in UpGrade; perhaps we should discuss at tomorrow's meeting.  But the Mathia data model permits this, so we have to allow it.

**Comment by JD2455** [comment]
setWorkingGroup function has been updated to support multiple values.
