### ISSUE TITLE
Need types for responses

### ISSUE THREAD

**Issue by alittlebrighter** [CarnegieLearningWeb/educational-experiment-service-client-libs#6]
Every function returns `Promise<Interfaces.IResponse>` (or the return type is undefined).  Without any sense of what is coming back, there is no way to determine what the client needs to do with the responses.

**Comment by jerith666** [comment]
@VivekFitkariwala and I talked about this briefly in the weekly A/B testing status meeting.  He's planning to rework this code so it uses the types from https://github.com/CarnegieLearningWeb/educational-experiment-types.

**Comment by VivekFitkariwala** [comment]
Repo is updated the response types.
