### ISSUE TITLE
export types with npm package

### ISSUE THREAD

**Issue by alittlebrighter** [CarnegieLearningWeb/educational-experiment-service-client-libs#62]
Currently just the compiled javascript is being published to the package.  Please include the Typescript types in the package.

**Comment by jerith666** [comment]
cc @mfugate1

**Comment by jerith666** [comment]
pinging this issue as it's blocking fixing CL's portal code.

**Comment by jerith666** [comment]
Per @kschaefe:

> I need the actual typings files.  They end `.d.ts` and are missing from the produced bundle.
> @mfugate can't package them because the typings aren't even built when I run npm build locally.

**Comment by nirmalpatel** [comment]
@jerith666 @kschaefe From @JD2455 

> It generates .d.ts file in the library by running the command `npm run build`
> It generates bundle.js file along with d.ts files

<img width="1440" alt="Screenshot 2021-01-28 at 10 36 17 PM" src="https://user-images.githubusercontent.com/830400/106173803-57d01c80-61ba-11eb-95f0-968b5bceee35.png">

**Comment by kschaefe** [comment]
Then, you need to add the types to the `package.json`, so that we can get the types when installing the package.

**Comment by nirmalpatel** [comment]
Cool, I'm not sure about JD's availability tomorrow (he is working full time on another project) so if this is a simple change, it would be a good idea if you can do it @kschaefe Otherwise JD will get back as soon as he gets time.

**Comment by nirmalpatel** [comment]
@kschaefe Can you clarify what you mean? Our code is producing the .d.ts files. What is the next step after that to solve the issue?

**Comment by kschaefe** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

You need to add `types` or `typings` to the `package.json` file.  These are not being picked up automatically  in the bundle because the directory structure in the bundle is incorrect.

**Comment by JD2455** [comment]
@jerith666 @nirmalpatel @kschaefe  I've added types to the package.json file.

**Comment by jerith666** [comment]
The solution is #70 for those playing along at home.  :)

**Comment by kschaefe** [comment]
Closing.  Resolved per #70.
